### ISSUE TITLE
Bumper car example not compiling anymore

### ISSUE THREAD

**Issue by Clindbergh** [SchoolAI/loro-extended#3]
```typescript
loro-extended/examples/bumper-cars/src/shared/types.ts:92
  color: Shape.plain.string().placeholder(CAR_COLORS[0]),
                              ^

TypeError: Shape.plain.string(...).placeholder is not a function
    at <anonymous> (loro-extended/examples/bumper-cars/src/shared/types.ts:92:31)
    at ModuleJob.run (node:internal/modules/esm/module_job:370:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:99:5)
```

It used to work fine in 0.6.0.

**Comment by canadaduane** [comment]
This is fixed in 5.4.0, thanks for reporting!
